### ISSUE TITLE
API returning 500 responses

### ISSUE THREAD

**Issue by calebcartwright** [ossf/scorecard-webapp#116]
Not sure if I've got the correct repository so please feel free to transfer or let me know the right repo to report this.

Over at Shields.io we consume a scorecard api at https://api.securityscorecards.dev/projects/:host/:org/:repo. At some point over the last few weeks this endpoint started returning a 500 response for repositories that haven't enabled the service/haven't been scanned, and response also includes an error "error pulling from GCS bucket"

```
$ curl -i https://api.securityscorecards.dev/projects/github.com/badges/shields
HTTP/2 500 
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
x-cloud-trace-context: 08b36f664a2e6adfd3e39e0fefbe9e58;o=1
date: Sun, 12 Jun 2022 23:57:21 GMT
server: Google Frontend
content-length: 30

error pulling from GCS bucket
```

Whereas this was previously returning a typical/expected 404 response code (more background in https://github.com/badges/shields/pull/7687#issuecomment-1091871943). The API still works fine for repositories that have been enabled/scanned

**Comment by azeemshaikh38** [comment]
This might be due to some recent changes that got submitted. It should not be returning `500`. Will try to send out a fix for this soon.
