### ISSUE TITLE
BUG: error processing signature

### ISSUE THREAD

**Issue by ben-manes** [ossf/scorecard-webapp#333]
> 2023/02/19 23:34:28 error processing signature: executing scorecard-api call: Post "https://api.securityscorecards.dev/projects/github.com/ben-manes/caffeine": context deadline exceeded

See [github action](https://github.com/ben-manes/caffeine/actions/runs/4218670268). Fails on the first attempt, succeeds on the second. Appears to be an intermittent problem that has occurred on multiple runs.

**Comment by ben-manes** [comment]
Happening again
https://github.com/ben-manes/caffeine/actions/runs/5679780844/job/15392599301

**Comment by spencerschrock** [comment]
> Happening again https://github.com/ben-manes/caffeine/actions/runs/5679780844/job/15392599301

We had an API outage that was resolved an hour ago. Since the issue was opened we've also added a retry, which should help with the initial intermittent problem.

**Comment by ben-manes** [comment]
wonderful, thanks! I'll close for now since it's understood and hopefully resolved.
