### ISSUE TITLE
feature request: scorecard result viewer should support a repo name option

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard-webapp#415]
So right now the viewer is opened with a link like this:
https://securityscorecards.dev/viewer/?platform=github.com&org=ossf&repo=scorecard

But it may nice to support something like one of these 
* https://securityscorecards.dev/viewer/github.com/ossf/scorecard
* https://securityscorecards.dev/viewer/?uri=github.com/ossf/scorecard

The first option is something that would be done in our router config, but I wasn't able to get this working:

```
router: {
    extendRoutes(routes, resolve) {
      routes.push({
        path: '/viewer/:platform/:org/:repo',
        redirect: to => {
          return { 
            path: '/viewer/', 
            query: { 
              platform: to.params.platform,
              org: to.params.org,
              repo: to.params.repo
            } 
          }
        },
      },)
    }
  }
```

The second option could be done by modifying the static JS to include something like this somewhere:
```
[platform, org, repo] = params.uri.split('/')
```

**Comment by cynthia-sg** [comment]
> https://securityscorecards.dev/viewer/?uri=github.com/ossf/scorecard

I'd be happy to take care of this one if you'd like :slightly_smiling_face:

**Comment by spencerschrock** [comment]
Thanks!
