### ISSUE TITLE
Viewer should display which version of Scorecard calculated the score

### ISSUE THREAD

**Issue by pnacht** [ossf/scorecard-webapp#441]
If a project has installed the Scorecard Action, the Action's result takes precedence over what's calculated by the cronjob. However, if the Action isn't up-to-date, it may be running an old version of Scorecard, which can impact the project's score.

Therefore, the viewer should display the version of Scorecard used to calculate that score, something like this:

![Screenshot 2023-07-19 at 17 18 59](https://github.com/ossf/scorecard-webapp/assets/115742393/df401923-5f07-4b3c-8b57-6176dd420f3c)

(Maybe add an alert if it isn't running the most recent version, so readers are aware?)

**Comment by spencerschrock** [comment]
Would you like to take a stab at this? It should be possible to use the "GENERATED AT" field as a guide.

**Comment by pnacht** [comment]
Eventually yes, but I don't have the bandwidth right now.
