### ISSUE TITLE
npm vulnerabilities 

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard-webapp#46]
With the latest code merges these vulnerabilities are reported by dependabot for this repository.

![image](https://user-images.githubusercontent.com/172697/158418691-127e289d-40a8-45f7-aa25-4eba85480580.png)

**Comment by naveensrinivasan** [comment]
@azeemshaikh38  Can you please assign it to the team who is working on this?

**Comment by azeemshaikh38** [comment]
Mark, we are seeing some vulnerabilities being reported (one of them with *High* severity). Could you please look into this?

**Comment by naveensrinivasan** [comment]
These have been addressed. Closing it.
